[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  # Pass required Firebase environment variables during build
  VITE_FIREBASE_API_KEY = "your-api-key"
  VITE_FIREBASE_AUTH_DOMAIN = "phuturesync.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "phuturesync"
  VITE_FIREBASE_STORAGE_BUCKET = "phuturesync.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "484050002731"
  VITE_FIREBASE_APP_ID = "1:484050002731:web:ad7d695435e2149ec05b6e"
  VITE_FIREBASE_MEASUREMENT_ID = "G-NBW3W9LJ4V"

# Redirects for SPA routing to allow React Router navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "
      default-src 'self';
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.firebaseapp.com https://firebaseinstallations.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
    "
