[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirects for SPA routing to allow React Router navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "
      default-src 'self';
      connect-src 'self' https://*.firebaseio.com https://*.googleapis.com https://*.firebaseapp.com https://firebaseinstallations.googleapis.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
    "
